#!/usr/bin/env bash
#systemctl list-unit-files --type=service | grep "enabled" | awk -F'.service' '{print $1}'


accounts-daemon
anacron
autovt@
avahi-daemon
bluetooth
console-setup
cron
cups-browsed
cups
dbus-org.bluez
dbus-org.freedesktop.Avahi
dbus-org.freedesktop.ModemManager1
dbus-org.freedesktop.nm-dispatcher
display-manager
getty@
keyboard-setup
lightdm
live-config
live-tools
lm-sensors
minissdpd
ModemManager
network-manager
networking
NetworkManager-dispatcher
NetworkManager-wait-online
NetworkManager
pppd-dns
rsync
rsyslog
rtkit-daemon
ssh
sshd
syslog
systemd-timesyncd
